#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Input
{
    public static class InputAssetsGenerator
    {
        private const string OutputPath = "Assets/Features/Input/Generated/InputAssets.g.cs";
        private const string RegistryAssetPath = "Assets/Features/Input/Generated/InputAssetsRegistry.asset";

        [MenuItem("Tools/Input/Generate Assets")]
        public static void Generate()
        {
            try
            {
                var mappingGuids = AssetDatabase.FindAssets("t:Input.InputMappingObject");
                var mappings = mappingGuids
                    .Select(g => AssetDatabase.LoadAssetAtPath<InputMappingObject>(AssetDatabase.GUIDToAssetPath(g)))
                    .Where(m => m != null)
                    .OrderBy(m => m.name)
                    .ToList();

                var registryEntries = new List<InputAssetsRegistry.Entry>();
                var uniqueRegistryGuids = new HashSet<string>(StringComparer.Ordinal);

                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated>");
                sb.AppendLine("// This file is generated by InputAssetsGenerator.");
                sb.AppendLine("// </auto-generated>");
                sb.AppendLine();
                sb.AppendLine("using System.Collections.Generic;");
                sb.AppendLine("using UnityEngine;");
                sb.AppendLine("#if UNITY_EDITOR");
                sb.AppendLine("using UnityEditor;");
                sb.AppendLine("#endif");
                sb.AppendLine();
                sb.AppendLine("namespace Input");
                sb.AppendLine("{");
                sb.AppendLine("    internal static class InputAssetsLoader");
                sb.AppendLine("    {");
                sb.AppendLine("        private static readonly Dictionary<string, Object> Cache = new Dictionary<string, Object>();");
                sb.AppendLine("        private static InputAssetsRegistry Registry;");
                sb.AppendLine("        private static bool RegistryLoaded;");
                sb.AppendLine();
                sb.AppendLine("        private static void EnsureRegistryLoaded()");
                sb.AppendLine("        {");
                sb.AppendLine("            if (RegistryLoaded) return;");
                sb.AppendLine("            RegistryLoaded = true;");
                sb.AppendLine("            Registry = InputAssetsRegistry.Instance;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        public static T Load<T>(string guid, string resourcesPath) where T : Object");
                sb.AppendLine("        {");
                sb.AppendLine("            if (string.IsNullOrEmpty(guid)) return null;");
                sb.AppendLine("            if (Cache.TryGetValue(guid, out var cached) && cached is T typed) return typed;");
                sb.AppendLine("#if UNITY_EDITOR");
                sb.AppendLine("            var path = AssetDatabase.GUIDToAssetPath(guid);");
                sb.AppendLine("            var asset = AssetDatabase.LoadAssetAtPath<T>(path);");
                sb.AppendLine("#else");
                sb.AppendLine("            T asset = null;");
                sb.AppendLine("            EnsureRegistryLoaded();");
                sb.AppendLine("            if (Registry != null && Registry.TryGet(guid, out T registryAsset))");
                sb.AppendLine("                asset = registryAsset;");
                sb.AppendLine("            if (!string.IsNullOrEmpty(resourcesPath))");
                sb.AppendLine("                asset ??= Resources.Load<T>(resourcesPath);");
                sb.AppendLine("#endif");
                sb.AppendLine("            if (asset != null) Cache[guid] = asset;");
                sb.AppendLine("            return asset;");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine("    public static class InputRegistry");
                sb.AppendLine("    {");

                foreach (var mapping in mappings)
                {
                    var mappingClass = SanitizeIdentifier(StripPrefix(mapping.name, "IM_"));
                    if (string.IsNullOrWhiteSpace(mappingClass)) mappingClass = SanitizeIdentifier(mapping.name);

                    var mappingGuid = AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(mapping));
                    var mappingResourcesPath = GetResourcesPath(mapping);
                    AddRegistryEntry(registryEntries, uniqueRegistryGuids, mappingGuid, mapping);

                    sb.AppendLine($"        public static class {mappingClass}");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            public static InputMappingObject Mapping => InputAssetsLoader.Load<InputMappingObject>(\"{mappingGuid}\", {ToLiteral(mappingResourcesPath)});");
                    sb.AppendLine();

                    var usedNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                    if (mapping.actions != null)
                    {
                        foreach (var action in mapping.actions.Where(a => a != null))
                        {
                            var actionName = StripPrefix(action.name, "IA_");
                            var propName = MakeUnique(usedNames, SanitizeIdentifier(actionName));

                            var actionGuid = AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(action));
                            var actionResourcesPath = GetResourcesPath(action);
                            AddRegistryEntry(registryEntries, uniqueRegistryGuids, actionGuid, action);

                            sb.AppendLine($"            public static InputActionObject {propName} => InputAssetsLoader.Load<InputActionObject>(\"{actionGuid}\", {ToLiteral(actionResourcesPath)});");
                        }
                    }

                    sb.AppendLine("        }");
                    sb.AppendLine();
                }

                sb.AppendLine("    }");
                sb.AppendLine("}");

                Directory.CreateDirectory(Path.GetDirectoryName(OutputPath)!);
                File.WriteAllText(OutputPath, sb.ToString(), new UTF8Encoding(false));

                GenerateRegistryAsset(registryEntries);
                EnsureRegistryIsPreloaded();

                AssetDatabase.SaveAssets();
                AssetDatabase.Refresh();

                Debug.Log($"InputAssetsGenerator: Generated at {OutputPath}");
            }
            catch (Exception ex)
            {
                Debug.LogError($"InputAssetsGenerator: Failed to generate. {ex}");
            }
        }

        private static string StripPrefix(string value, string prefix)
        {
            if (string.IsNullOrEmpty(value)) return value;
            return value.StartsWith(prefix, StringComparison.OrdinalIgnoreCase)
                ? value.Substring(prefix.Length)
                : value;
        }

        private static string SanitizeIdentifier(string value)
        {
            if (string.IsNullOrWhiteSpace(value)) return "_";
            var sb = new StringBuilder();

            for (int i = 0; i < value.Length; i++)
            {
                var c = value[i];
                if (char.IsLetterOrDigit(c) || c == '_')
                    sb.Append(c);
                else if (char.IsWhiteSpace(c) || c == '-' || c == '.')
                    sb.Append('_');
            }

            var result = sb.ToString();
            if (string.IsNullOrWhiteSpace(result)) result = "_";
            if (char.IsDigit(result[0])) result = "_" + result;
            return result;
        }

        private static string MakeUnique(HashSet<string> used, string baseName)
        {
            if (used.Add(baseName)) return baseName;
            int i = 2;
            while (!used.Add($"{baseName}_{i}")) i++;
            return $"{baseName}_{i}";
        }

        private static string GetResourcesPath(UnityEngine.Object asset)
        {
            var path = AssetDatabase.GetAssetPath(asset);
            var idx = path.IndexOf("/Resources/", StringComparison.OrdinalIgnoreCase);
            if (idx < 0) return null;

            var resourcesPath = path.Substring(idx + "/Resources/".Length);
            return Path.ChangeExtension(resourcesPath, null).Replace("\\", "/");
        }

        private static string ToLiteral(string value)
        {
            return value == null ? "null" : $"\"{value}\"";
        }

        private static void AddRegistryEntry(List<InputAssetsRegistry.Entry> entries, HashSet<string> uniqueGuids, string guid, UnityEngine.Object asset)
        {
            if (string.IsNullOrEmpty(guid) || asset == null)
            {
                return;
            }
            if (!uniqueGuids.Add(guid))
            {
                return;
            }

            entries.Add(new InputAssetsRegistry.Entry
            {
                guid = guid,
                asset = asset
            });
        }

        private static void GenerateRegistryAsset(List<InputAssetsRegistry.Entry> entries)
        {
            string registryDirectory = Path.GetDirectoryName(RegistryAssetPath);
            if (!string.IsNullOrEmpty(registryDirectory))
            {
                Directory.CreateDirectory(registryDirectory);
            }

            InputAssetsRegistry registry = AssetDatabase.LoadAssetAtPath<InputAssetsRegistry>(RegistryAssetPath);
            if (registry == null)
            {
                registry = ScriptableObject.CreateInstance<InputAssetsRegistry>();
                AssetDatabase.CreateAsset(registry, RegistryAssetPath);
            }

            registry.SetEntries(entries);
        }

        private static void EnsureRegistryIsPreloaded()
        {
            InputAssetsRegistry registry = AssetDatabase.LoadAssetAtPath<InputAssetsRegistry>(RegistryAssetPath);
            if (registry == null)
            {
                return;
            }

            UnityEngine.Object[] preloadedAssets = PlayerSettings.GetPreloadedAssets();
            List<UnityEngine.Object> updated = new List<UnityEngine.Object>(preloadedAssets.Length + 1);
            bool hasRegistry = false;

            for (int i = 0; i < preloadedAssets.Length; i++)
            {
                UnityEngine.Object preloadedAsset = preloadedAssets[i];
                if (!preloadedAsset)
                {
                    continue;
                }

                if (preloadedAsset == registry)
                {
                    hasRegistry = true;
                }

                updated.Add(preloadedAsset);
            }

            if (!hasRegistry)
            {
                updated.Add(registry);
                PlayerSettings.SetPreloadedAssets(updated.ToArray());
            }
        }
    }
}
#endif